# fly.toml app configuration file generated for zakat-reminder on 2024-09-10T14:13:16-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zakat-reminder'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
